apiVersion: batch/v1
kind: Job
metadata:
  name: will-be-overridden
spec:
  template:
    spec:
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: cephfs-pvc
            readOnly: false
      containers:
        - name: job
          image: bash
          volumeMounts:
            - mountPath: /input
              name: inputs
              subPath: somepath
      restartPolicy: Never
