apiVersion: batch/v1
kind: Job
metadata:
  name: will-be-overridden
spec:
  template:
    spec:
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: default-pvc
            readOnly: false
      containers:
        - name: job
          image: bash
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
          volumeMounts:
            - mountPath: /input
              name: inputs
              subPath: somepath
      restartPolicy: Never
  backoffLimit: 0
