apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  template:
    spec:
      containers:
        - name: testjob
          image: bash
          command: ["sleep", "20"]
      restartPolicy: Never
  backoffLimit: 1
