apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-volume
spec:
  storageClassName: gce-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: migration
spec:
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: default-pvc
        readOnly: false
    - name: backup
      persistentVolumeClaim:
        claimName: backup-volume
        readOnly: false
  terminationGracePeriodSeconds: 5
  priorityClassName: highest-priority
  containers:
    - name: ubuntu
      command: ["sh"]
      args: ["-c", "sleep 30d"]
      image: ubuntu:latest
      imagePullPolicy: "Always"
      volumeMounts:
        - name: nfs
          mountPath: /volume
        - name: backup
          mountPath: /backup
---

