---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: $TOTALSTORAGE
  storageClassName: csi-cephfs
