# Generated by Django 2.2.6 on 2019-10-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_ran', models.DateTimeField()),
            ],
        ),
    ]
