# Generated by Django 2.2.6 on 2019-10-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeImage',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('labels_string', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='NodeImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_refs', to='app.NodeImage')),
            ],
        ),
    ]
