# Generated by Django 2.2.6 on 2019-10-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_globals'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeimage',
            name='cmd_string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nodeimage',
            name='labels_string',
            field=models.TextField(default=''),
        ),
    ]
