# Generated by Django 2.2.6 on 2019-10-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191016_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeimage',
            name='env_string',
            field=models.TextField(default=''),
        ),
    ]
