# Generated by Django 2.2.6 on 2019-10-25 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_nodeimage_env_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='nodeimage',
            name='cmd_string',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='nodeimage',
            name='env_string',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='nodeimage',
            name='labels_string',
            field=models.TextField(default='{}'),
        ),
    ]
