# Generated by Django 2.2.6 on 2019-10-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_job_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
