# Generated by Django 2.2.6 on 2019-10-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='job_count',
            field=models.CharField(choices=[('auto', 'Auto'), ('single', 'Single'), ('multiple', 'Multiple')], default='auto', max_length=16),
        ),
    ]
