# Generated by Django 2.2.6 on 2019-10-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_upload_job_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
