# Generated by Django 2.2.6 on 2019-10-29 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_workflow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='should_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
    ]
