# Generated by Django 2.2.6 on 2019-10-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191029_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dependencies_met',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Workflow'),
        ),
    ]
