# Generated by Django 2.2.6 on 2019-10-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191029_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='app.Job'),
        ),
    ]
