# Generated by Django 2.2.6 on 2019-10-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20191031_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_newest',
            field=models.BooleanField(default=True),
        ),
    ]
