# Generated by Django 2.2.6 on 2019-11-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeimage',
            name='entrypoint_string',
            field=models.TextField(default='[]'),
        ),
    ]
