# Generated by Django 2.2.6 on 2019-11-10 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_nodeimage_entrypoint_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='globals',
            name='log_chars_kept',
            field=models.IntegerField(default=1000),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(max_length=256)),
                ('long_text', models.TextField()),
                ('importance', models.IntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
