# Generated by Django 2.2.6 on 2019-11-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='parallel_runs',
            field=models.IntegerField(default=-1),
        ),
    ]
