# Generated by Django 2.2.6 on 2019-11-18 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_job_parallel_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='globals',
            name='some_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
