# Generated by Django 2.2.6 on 2019-11-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_nodeimage_override_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeimage',
            name='env_string',
            field=models.TextField(default='{}'),
        ),
    ]
