# Generated by Django 2.2.6 on 2019-12-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20191128_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='reassembling',
            field=models.BooleanField(default=False),
        ),
    ]
