# Generated by Django 2.2.6 on 2019-12-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_upload_reassembling'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='extracting',
            field=models.BooleanField(default=False),
        ),
    ]
