# Generated by Django 2.2.6 on 2019-12-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_upload_extracting'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
