# Generated by Django 2.2.8 on 2019-12-10 19:53

import app.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_workflow_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='name',
            field=models.CharField(blank=True, default=app.util.default_name, max_length=64),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(default=app.util.default_name, max_length=64),
        ),
    ]
