# Generated by Django 2.2.8 on 2019-12-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20191210_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=36)),
                ('num', models.CharField(blank=True, default='', max_length=8)),
                ('pod', models.CharField(blank=True, default='', max_length=5)),
                ('cpu', models.FloatField(default=-1.0)),
                ('memory', models.FloatField(default=-1.0)),
            ],
        ),
    ]
