# Generated by Django 2.2.8 on 2019-12-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_resourceusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceusage',
            old_name='cpu',
            new_name='max_cpu',
        ),
        migrations.RenameField(
            model_name='resourceusage',
            old_name='memory',
            new_name='max_memory',
        ),
    ]
