# Generated by Django 2.2.8 on 2019-12-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20191210_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
