# Generated by Django 2.2.8 on 2019-12-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_workflow_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished_runs',
            field=models.IntegerField(default=0),
        ),
    ]
