# Generated by Django 2.2.8 on 2019-12-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_job_should_notify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
