# Generated by Django 2.2.8 on 2019-12-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20191212_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
