# Generated by Django 2.2.8 on 2019-12-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20191212_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scheduled_runs',
            field=models.IntegerField(default=0),
        ),
    ]
