# Generated by Django 2.2.8 on 2020-01-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_job_scheduled_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='retries_left',
            field=models.IntegerField(default=0),
        ),
    ]
