# Generated by Django 2.2.8 on 2020-01-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_job_retries_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='retries_left',
        ),
        migrations.CreateModel(
            name='JobRetries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retries', models.IntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retries', to='app.Job')),
            ],
        ),
    ]
