# Generated by Django 2.2.8 on 2020-01-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_jobretries_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='updated_resources',
            field=models.BooleanField(default=False),
        ),
    ]
