# Generated by Django 2.2.8 on 2020-01-30 22:13

import app.models.api_token
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0047_job_resource_exhaustion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('token', models.CharField(default=app.models.api_token.new_token, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
