# Generated by Django 2.2.8 on 2020-01-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_apiworkflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiworkflow',
            name='outputs_count',
            field=models.IntegerField(default=-1),
        ),
    ]
