# Generated by Django 2.2.8 on 2020-02-01 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_apiworkflow_outputs_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='api_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ApiWorkflow'),
        ),
    ]
