# Generated by Django 2.2.8 on 2020-02-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_workflow_api_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='job_count',
        ),
    ]
