# Generated by Django 2.2.8 on 2020-02-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_upload_job_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='size',
            field=models.FloatField(default=-1.0),
        ),
    ]
