# Generated by Django 2.2.8 on 2020-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20200212_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='globals',
            name='nodes_string',
            field=models.TextField(default='[]'),
        ),
    ]
