# Generated by Django 2.2.8 on 2020-02-24 18:26

import app.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_globals_nodes_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiworkflow',
            name='created_at',
            field=models.DateTimeField(default=app.util.now),
        ),
        migrations.AddField(
            model_name='apiworkflow',
            name='run_at',
            field=models.DateTimeField(default=app.util.now),
        ),
    ]
