# Generated by Django 2.2.10 on 2020-03-17 21:24

import app.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_upload_no_extract'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='finished_at',
            field=models.DateTimeField(default=app.util.now),
        ),
    ]
