# Generated by Django 2.2.10 on 2020-03-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_upload_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='finished_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
