# Generated by Django 2.2.10 on 2020-03-21 20:22

import app.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20200317_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='finished_at',
            field=models.DateTimeField(default=app.util.now),
        ),
    ]
