apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: default-priority
value: 10000
globalDefault: true
description: "-"
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: highest-priority
value: 999999999
globalDefault: false
description: "-"
