name: Build

on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Build the Docker image
      - name: Build
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin;
          echo $GITHUB_SHA > .commit;
          docker build . -t bromberglab/bio-node-webserver;
          docker push bromberglab/bio-node-webserver;
